feat: Add 'rm' command
RosetteOS/Rosebush pull request #11
Opened 2021-06-19 15:16 UTC by danitw

2021-06-19 16:03 UTC, TorchedSammy commented
u forgot to add rm to the makefile!!

2021-06-19 16:05 UTC, danitw commented
> u forgot to add rm to the makefile!!

ah sorry, I had forgotten

2021-06-19 16:08 UTC, TorchedSammy commented
also, this deletes empty directories. which it shouldnt do, it should still need -r

2021-06-19 16:11 UTC, danitw commented
> also, this deletes empty directories. which it shouldnt do, it should still need -r

forgot to dial the code?

2021-06-19 16:13 UTC, TorchedSammy commented
![](https://modeus.is-inside.me/DuphQu0C.png)
deleting empty directory shown here
also, `-r` doesnt work anyways

2021-06-19 16:15 UTC, danitw commented
>  deleting empty directory shown here

weird, i tested it and it was working, I will look here

2021-06-19 16:18 UTC, TorchedSammy commented
why does `-r` use `RemoveAll` in a loop but normally uses `Remove`?

2021-06-19 16:20 UTC, TorchedSammy commented
oh i see, options only work when theyre first. let's use getopt for options like in cat

2021-06-19 16:22 UTC, danitw commented
> oh i see, options only work when theyre first. let's use getopt for options like in cat

ok,I will change here

2021-06-19 16:26 UTC, danitw commented
> why does `-r` use `RemoveAll` in a loop but normally uses `Remove`?

removeall deletes whatever and all the children there, removes only the file

2021-06-19 16:31 UTC, TorchedSammy requested changes

2021-06-19 16:31 UTC, TorchedSammy commented on rm/rm.go
> +		args := removeIndex(args, 0)
this function is unnecessary. its only used here and u can remove the first with `args[1:]` like u did before

2021-06-19 16:33 UTC, TorchedSammy commented
> removeall deletes whatever and all the children there, removes only the file
ok, i understand how it works now, for some reason i thought the array had files and u were trying to removeall on files and not directories

2021-06-19 16:34 UTC, TorchedSammy commented on rm/rm.go
> +		for _, v := range args {
a better variable name can be used

2021-06-19 16:35 UTC, TorchedSammy requested changes

2021-06-19 16:35 UTC, TorchedSammy commented on rm/rm.go
> +	for _, v := range args {
use better variable name

2021-06-19 16:36 UTC, danitw commented on rm/rm.go
> +		args := removeIndex(args, 0)
ah yes, i forgot

2021-06-19 16:37 UTC, danitw commented
> > removeall deletes whatever and all the children there, removes only the file
> 
> ok, i understand how it works now, for some reason i thought the array had files and u were trying to removeall on files and not directories

klasjdsa, it happens

2021-06-21 10:15 UTC, TorchedSammy commented on rm/rm.go
> +	r := getopt.String('r', "")
u could change var name to recursive
but the main fix i want u to do is change this to `BoolLong`, since we also want to accept the long option of `--recursive`

2021-06-21 10:15 UTC, TorchedSammy commented on rm/rm.go
> +	if *r != "" {
so now u just check if *r

2021-06-21 10:16 UTC, TorchedSammy commented on rm/rm.go
> +
and remove this reused code

2021-06-21 10:18 UTC, TorchedSammy commented on rm/rm.go
> +			return
the loop here should continue instead of stop

2021-06-21 10:19 UTC, TorchedSammy requested changes

2021-06-21 10:19 UTC, TorchedSammy commented on rm/rm.go
> +		return
why do we return here?

2021-06-21 14:24 UTC, danitw commented on rm/rm.go
> +		return
I don't remember why I put this, it must have been a mistake since this return is useless there

2021-06-21 15:31 UTC, TorchedSammy requested changes
besides my requested changes, looks good to me

2021-06-21 15:31 UTC, TorchedSammy commented on rm/rm.go
> +	recursive := getopt.BoolLong("recursive", 'r')
BoolLong takes an extra argument which is the description to show in the help message

2021-06-21 15:31 UTC, TorchedSammy commented on rm/rm.go
> +		return
should remove it then

2021-06-21 15:32 UTC, danitw commented
> besides my requested changes, looks good to me

hmmm, how nice

2021-06-21 21:18 UTC, TorchedSammy approved these changes

2021-06-21 21:18 UTC, TorchedSammy commented
there's a little tiny change i'd like but dont worry ill do it myself

2021-06-21 21:19 UTC, merged