feat: add 'sleep' command
RosetteOS/Rosebush pull request #13
Opened 2021-06-28 21:04 UTC by danitw

2021-06-28 21:52 UTC, TorchedSammy commented
https://github.com/RosetteOS/Rosebush/pull/13/commits/f762e65c1410801c377d004d4a4c31a5a6748145's type should be chore and https://github.com/RosetteOS/Rosebush/pull/13/commits/47ac59e5fde5d25cd1201362a56d0919b585f173's commit message should be changed to `build: add sleep to makefile`

2021-06-28 21:54 UTC, TorchedSammy commented
you uploaded the sleep binary since u didnt build it to the ignored bin directory

2021-06-28 22:00 UTC, TorchedSammy commented on sleep/sleep.go
> +	last := arg[len(arg)-1:]
space between binary ops (`-`)

2021-06-28 22:00 UTC, TorchedSammy commented on sleep/sleep.go
> +		temp, err = strconv.ParseInt(arg[:len(arg)-1], 10, 64)
space between binary ops

2021-06-28 22:01 UTC, TorchedSammy commented on sleep/sleep.go
> +	var temp int64
this var can be renamed to duration

2021-06-28 22:02 UTC, TorchedSammy requested changes
mostly style changes
also please remove the extra newline between variable declarations

2021-06-29 18:05 UTC, danitw commented
> you uploaded the sleep binary since u didnt build it to the ignored bin directory; delete it

i did not understand

2021-06-29 18:07 UTC, danitw commented on sleep/sleep.go
> +	last := arg[len(arg)-1:]
fmt don't let

2021-06-29 18:07 UTC, danitw commented on sleep/sleep.go
> +		temp, err = strconv.ParseInt(arg[:len(arg)-1], 10, 64)
fmt don't let

2021-06-30 00:57 UTC, TorchedSammy commented
this pr is a little broken: makefile has a conflict and commits from `rm` are included

2021-06-30 17:35 UTC, closed without merging